apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-frontend
  namespace: loan-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-frontend
  template:
    metadata:
      labels:
        app: loan-frontend
    spec:
      containers:
        - name: frontend
          image: loan-manager-frontend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            # runtime config.js for SPA
            - name: app-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
            # nginx proxy config to backend Service
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: app-config
          configMap:
            name: loan-config
        - name: nginx-conf
          configMap:
            name: loan-frontend-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: loan-frontend
  namespace: loan-manager
spec:
  type: NodePort
  selector:
    app: loan-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001
